"""
Prompts Package
Centralized configuration for all prompts, messages, and system settings
"""

from .system_prompts import (
    SYSTEM_INSTRUCTIONS,
    PROCESSING_RULES,
    LOG_TEMPLATES,
    ERROR_MESSAGES,
    SYSTEM_MESSAGES,
    COORDINATION_RULES
)

from .user_prompts import (
    GREETING_TEMPLATES,
    CREDIT_ANALYSIS_MESSAGES,
    EMPLOYMENT_MESSAGES,
    COLLATERAL_MESSAGES,
    CRITIQUE_MESSAGES,
    DECISION_REASONING,
    PLANNER_MESSAGES,
    STATUS_LABELS,
    RISK_LABELS,
    VERIFICATION_LABELS
)

from .config import (
    RISK_THRESHOLDS,
    CREDIT_SCORE_PARAMS,
    LTV_CONFIG,
    KNOWN_COMPANIES,
    RISK_WEIGHTS,
    STATUS_FLOW,
    VERIFICATION_CRITERIA
)

__all__ = [
    # System Prompts
    'SYSTEM_INSTRUCTIONS',
    'PROCESSING_RULES',
    'LOG_TEMPLATES',
    'ERROR_MESSAGES',
    'SYSTEM_MESSAGES',
    'COORDINATION_RULES',
    
    # User Prompts
    'GREETING_TEMPLATES',
    'CREDIT_ANALYSIS_MESSAGES',
    'EMPLOYMENT_MESSAGES',
    'COLLATERAL_MESSAGES',
    'CRITIQUE_MESSAGES',
    'DECISION_REASONING',
    'PLANNER_MESSAGES',
    'STATUS_LABELS',
    'RISK_LABELS',
    'VERIFICATION_LABELS',
    
    # Configuration
    'RISK_THRESHOLDS',
    'CREDIT_SCORE_PARAMS',
    'LTV_CONFIG',
    'KNOWN_COMPANIES',
    'RISK_WEIGHTS',
    'STATUS_FLOW',
    'VERIFICATION_CRITERIA'
]
