#!/bin/bash

echo "=================================="
echo "🎨 Beautiful UI - Loan Approval AI"
echo "=================================="
echo ""
echo "✅ Server is running!"
echo ""
echo "🌟 Open this URL in your browser:"
echo ""
echo "    👉 http://localhost:8000/"
echo ""
echo "=================================="
echo ""
echo "Alternative URLs:"
echo "  • UI:          http://localhost:8000/ui"
echo "  • API Docs:    http://localhost:8000/docs"
echo "  • Health:      http://localhost:8000/health"
echo ""
echo "=================================="
echo ""
echo "💡 Quick Test:"
echo "  1. Open http://localhost:8000/ in browser"
echo "  2. Click '💪 Strong' preset button"
echo "  3. Click '🚀 Submit Application'"
echo "  4. Watch the magic happen! ✨"
echo ""
echo "=================================="
